http:
  port: "8081"
  
salesforce:
  username: ${SF_USERNAME}
  password: ${SF_PASSWORD}
  security-token: ${SF_SECURITY_TOKEN}
  
file:
  config:
    connection: 
      working-dir: ${WORKING_DIR}  
      
db:
  host: "iltdb.mule-training.com"
  port: "3306"
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}      
  
  
